version: '2'

volumes:
    osbsbox-osbs:
    osbsbox-koji-config:
    osbsbox-koji-certs:
    osbsbox-registry-auth:
    osbsbox-koji-data:
    osbsbox-koji-db:

services:

    shared-data:
        build:
          context: shared-data
        hostname: shared-data
        volumes:
            - osbsbox-osbs:/opt/osbs
            - osbsbox-koji-data:/mnt/koji
            - osbsbox-koji-config:/opt/koji-clients
            - osbsbox-koji-certs:/etc/pki/koji
            - osbsbox-registry-auth:/auth
            - ./certs:/certs:z

    koji-db:
        build: koji-db
        hostname: koji-db
        environment:
            - POSTGRES_DB=koji
            - POSTGRES_USER=koji
            - POSTGRES_PASSWORD=mypassword
        volumes:
            - osbsbox-koji-db:/var/lib/postgresql/data

    koji-hub:
        build:
          context: hub
        hostname: koji-hub
        volumes_from:
            - shared-data
        # Need to export ports on workstation so it
        # can be reached from Openshift's pods
        ports:
            - "8080:80"
            - "8083:8083"

    koji-builder:
        build:
          context: koji-builder
        privileged: true
        hostname: koji-builder
        volumes_from:
            - shared-data
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        tmpfs:
            - /run
            - /tmp

    koji-client:
        build:
          context: client
        hostname: koji-client
        volumes_from:
            - shared-data

    odcs-frontend:
        build:
            context: odcs
        command: start-odcs-frontend
        ports:
            - 5005:80
        volumes_from:
            - shared-data

    odcs-backend:
        build:
            context: odcs
        command: start-odcs-backend
        volumes_from:
            - shared-data

    pdc:
        build:
            context: pdc
        ports:
            - 5004:80

    registry:
      image: registry:2
      ports:
        - 5000:5000
      environment:
        REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
        REGISTRY_HTTP_TLS_KEY: /certs/domain.key
        REGISTRY_AUTH: htpasswd
        REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
        REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      volumes_from:
        - shared-data
